# Generated by Django 5.1.1 on 2024-10-03 11:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exceptionClass', models.CharField(help_text='Name and path of the exception class that was raised.', max_length=128)),
                ('message', models.CharField(help_text='Message of the exception', max_length=2048)),
                ('tbList', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(help_text='One line of the exception traceback formatted', max_length=1024), size=64)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(help_text='Unique Log ID, same across databases', primary_key=True, serialize=False)),
                ('logType', models.CharField(choices=[('Debug', 'D'), ('Info', 'I'), ('Warning', 'W'), ('Error', 'E'), ('Critical', 'C')], help_text='Log Type', max_length=8)),
                ('logEvent', models.IntegerField(help_text='Log Event NUmber')),
                ('logMessage', models.TextField(help_text='Log Message', max_length=500)),
                ('origin', models.CharField(default=None, help_text='Log Origin', max_length=500, null=True)),
                ('additionalData', models.JSONField(default=None, help_text='Additional Data', null=True)),
                ('logTime', models.DateTimeField(auto_now_add=True, help_text='Log Time')),
                ('exceptionObject', models.ForeignKey(blank=True, default=-1, help_text='Linked Exception Object', null=True, on_delete=django.db.models.deletion.CASCADE, to='canlog.exceptionmodel')),
                ('logUser', models.ForeignKey(default=-1, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
